## Build Image
kind: pipeline
name: default

steps:
- name: test
  image: digitalpatterns/node:4
  commands:
    - npm install
    - npm run cover
  when:
    event: push

- name: build_push_to_docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: digitalpatterns/form-api-server
    tags: ${DRONE_COMMIT_SHA}
  when:
    branch: master
    event: push

- name: deploy_to_elf
  image: quay.io/ukhomeofficedigital/kd
  secrets:
    - DEV_KUBE_SERVER
    - DEV_KUBE_PROTOCOL
    - DEV_KUBE_TOKEN
    - DEV_WHITELIST
    - DEV_KEYCLOAK_URL
    - DEV_KEYCLOAK_PROTOCOL
    - DEV_KEYCLOAK_REALM
    - DEV_NGINX_IMAGE
    - DEV_NGINX_TAG
    - DEV_DB_FORM_PORT
    - DEV_DB_FORM_HOSTNAME
    - DEV_DB_FORM_SSL
    - DEV_DB_FORM_DEFAULT_USERNAME
    - DEV_DB_FORM_DEFAULT_DBNAME
    - DEV_DB_FORM_DEFAULT_PASSWORD
    - DEV_API_FORM_NAME
    - DEV_API_FORM_IMAGE
    - DEV_API_FORM_KEYCLOAK_CLIENT_ID
    - DEV_API_FORM_KEYCLOAK_ADMIN_USERNAME
    - DEV_API_FORM_KEYCLOAK_ADMIN_PASSWORD
    - DEV_API_FORM_KEYCLOAK_ROLES
    - DEV_API_FORM_KUBE_NAMESPACE
    - DEV_API_FORM_LOG_ENABLE_CHANGE
    - DEV_API_FORM_LOG_CHANGE_TIMEOUT
    - DEV_API_FORM_LOG_ENABLE_QUERY
    - DEV_API_FORM_PORT
    - DEV_API_FORM_CORS_ORIGIN
  commands:
    - export KUBE_SERVER=$${DEV_KUBE_SERVER}
    - export KUBE_PROTOCOL=$${DEV_KUBE_PROTOCOL}
    - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
    - export WHITELIST=$${DEV_WHITELIST}
    - export KEYCLOAK_URL=$${DEV_KEYCLOAK_URL}
    - export KEYCLOAK_PROTOCOL=$${DEV_KEYCLOAK_PROTOCOL}
    - export KEYCLOAK_REALM=$${DEV_KEYCLOAK_REALM}
    - export NGINX_IMAGE=$${DEV_NGINX_IMAGE}
    - export NGINX_TAG=$${DEV_NGINX_TAG}
    - export DB_FORM_PORT=$${DEV_DB_FORM_PORT}
    - export DB_FORM_HOSTNAME=$${DEV_DB_FORM_HOSTNAME}
    - export DB_FORM_SSL=$${DEV_DB_FORM_SSL}
    - export DB_FORM_DEFAULT_USERNAME=$${DEV_DB_FORM_DEFAULT_USERNAME}
    - export DB_FORM_DEFAULT_DBNAME=$${DEV_DB_FORM_DEFAULT_DBNAME}
    - export DB_FORM_DEFAULT_PASSWORD=$${DEV_DB_FORM_DEFAULT_PASSWORD}
    - export API_FORM_NAME=$${DEV_API_FORM_NAME}
    - export API_FORM_IMAGE=$${DEV_API_FORM_IMAGE}
    - export API_FORM_KEYCLOAK_CLIENT_ID=$${DEV_API_FORM_KEYCLOAK_CLIENT_ID}
    - export API_FORM_KEYCLOAK_ADMIN_USERNAME=$${DEV_API_FORM_KEYCLOAK_ADMIN_USERNAME}
    - export API_FORM_KEYCLOAK_ADMIN_PASSWORD=$${DEV_API_FORM_KEYCLOAK_ADMIN_PASSWORD}
    - export API_FORM_KEYCLOAK_ROLES=$${DEV_API_FORM_KEYCLOAK_ROLES}
    - export API_FORM_KUBE_NAMESPACE=$${DEV_API_FORM_KUBE_NAMESPACE}
    - export API_FORM_LOG_ENABLE_CHANGE=$${DEV_API_FORM_LOG_ENABLE_CHANGE}
    - export API_FORM_LOG_CHANGE_TIMEOUT=$${DEV_API_FORM_LOG_CHANGE_TIMEOUT}
    - export API_FORM_LOG_ENABLE_QUERY=$${DEV_API_FORM_LOG_ENABLE_QUERY}
    - export API_FORM_PORT=$${DEV_API_FORM_PORT}
    - export API_FORM_CORS_ORIGIN=$${DEV_API_FORM_CORS_ORIGIN}
    - export API_FORM_TAG=${DRONE_COMMIT_SHA}
    - kd --insecure-skip-tls-verify -f kube/cert.yml
    - kd --insecure-skip-tls-verify -f kube/secret.yml
    - kd --insecure-skip-tls-verify -f kube/network-policy.yml
    - kd --insecure-skip-tls-verify -f kube/service.yml
    - kd --insecure-skip-tls-verify -f kube/deployment.yml
    - kd --insecure-skip-tls-verify -f kube/ingress.yml
  when:
    environment: dev
    event: deployment
