## Build Image
pipeline:

  tests:
    image: digitalpatterns/node:4
    commands:
      - npm install
      - npm run cover
    when:
      event: push

  build_push_to_ecr:
    image: quay.io/ukhomeofficedigital/ecr:latest
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/cop/form-api-server
    build_args:
      - APP_BUILD=${DRONE_COMMIT_SHA}
    tags:
      - ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_FORM_API_NAME
      - DEV_WHITELIST
      - DEV_FORM_API_KUBE_NAMESPACE
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_FORM_API_DB_USERNAME
      - DEV_FORM_API_DB_PASSWORD
      - DEV_FORM_API_DB_HOSTNAME
      - DEV_FORM_API_DB_NAME
      - DEV_FORM_API_DB_PORT
      - DEV_FORM_API_DB_SSL
      - DEV_KEYCLOAK_URL
      - DEV_FORM_API_KEYCLOAK_CLIENT_ID
      - DEV_KEYCLOAK_REALM
      - DEV_FORM_API_KEYCLOAK_ADMIN_USERNAME
      - DEV_FORM_API_KEYCLOAK_ADMIN_PASSWORD
      - DEV_FORM_API_KEYCLOAK_ADMIN_ROLES
      - DEV_FORM_API_LOG_ENABLE_CHANGE
      - DEV_FORM_API_LOG_CHANGE_TIMEOUT
      - DEV_FORM_API_CORS_ORIGIN
      - DEV_FORM_API_ENABLE_QUERY
      - DEV_FORM_API_PORT
    commands:
      - export FORM_API_NAME=$${DEV_FORM_API_NAME}
      - export WHITELIST=$${DEV_WHITELIST}
      - export FORM_API_KUBE_NAMESPACE=$${DEV_FORM_API_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export FORM_API_DB_USERNAME=$${DEV_FORM_API_DB_USERNAME}
      - export FORM_API_DB_PASSWORD=$${DEV_FORM_API_DB_PASSWORD}
      - export FORM_API_DB_HOSTNAME=$${DEV_FORM_API_DB_HOSTNAME}
      - export FORM_API_DB_NAME=$${DEV_FORM_API_DB_NAME}
      - export FORM_API_DB_PORT=$${DEV_FORM_API_DB_PORT}
      - export FORM_API_DB_SSL=$${DEV_FORM_API_DB_SSL}
      - export KEYCLOAK_URL=$${DEV_KEYCLOAK_URL}
      - export FORM_API_KEYCLOAK_CLIENT_ID=$${DEV_FORM_API_KEYCLOAK_CLIENT_ID}
      - export KEYCLOAK_REALM=$${DEV_KEYCLOAK_REALM}
      - export FORM_API_KEYCLOAK_ADMIN_USERNAME=$${DEV_FORM_API_KEYCLOAK_ADMIN_USERNAME}
      - export FORM_API_KEYCLOAK_ADMIN_PASSWORD=$${DEV_FORM_API_KEYCLOAK_ADMIN_PASSWORD}
      - export FORM_API_KEYCLOAK_ADMIN_ROLES=$${DEV_FORM_API_KEYCLOAK_ADMIN_ROLES}
      - export FORM_API_LOG_ENABLE_CHANGE=$${DEV_FORM_API_LOG_ENABLE_CHANGE}
      - export FORM_API_LOG_CHANGE_TIMEOUT=$${DEV_FORM_API_LOG_CHANGE_TIMEOUT}
      - export FORM_API_CORS_ORIGIN=$${DEV_FORM_API_CORS_ORIGIN}
      - export FORM_API_LOG_ENABLE_QUERY=$${DEV_FORM_API_LOG_ENABLE_QUERY}
      - export FORM_API_PORT=$${DEV_FORM_API_PORT}
      - export IMAGE_TAG=${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      environment: dev
      event: deployment
