version: '3.7'

volumes:
  postgres_data_form:
    driver: local

services:
  postgres_formapi:
    image: postgres:10-alpine
    restart: on-failure
    container_name: postgres_formapi
    volumes:
      - postgres_data_form:/var/lib/data/postgresqlform/data
    environment:
      POSTGRES_DB: formdb
      POSTGRES_USER: formuser
      POSTGRES_PASSWORD: password
    ports:
      - '5435:5432'
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U formuser formdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    labels:
      - "traefik.enable=false"

  formapi:
    build: .
    container_name: formapi
    environment:
      - NODE_ENV=production
      - FORM_API_DB_USERNAME=formuser
      - FORM_API_DB_PASSWORD=password
      - FORM_API_DB_NAME=formdb
      - FORM_API_DB_HOSTNAME=postgres_formapi
      - FORM_API_DB_PORT=5432
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_PROTOCOL=https://
      - FORM_API_KEYCLOAK_BEARER_ONLY=true
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - API_FORM_KEYCLOAK_ADMIN_USERNAME=${FORM_API_KEYCLOAK_ADMIN_USERNAME}
      - API_FORM_KEYCLOAK_ADMIN_PASSWORD=${FORM_API_KEYCLOAK_ADMIN_PASSWORD}
      - FORM_API_ADMIN_ROLES=platform
      - FORM_API_LOG_ENABLE_CHANGE=false
      - API_FORM_KEYCLOAK_CLIENT_ID=${FORM_API_KEYCLOAK_CLIENT_ID}
      - API_FORM_CORS_ORIGIN=http://localhost:3000
      - API_FORM_CORRELATION_ID_REQUEST_HEADER=correlationId
    depends_on:
      - postgres_formapi
    networks:
      - web
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 5s
      timeout: 2s
      retries: 15
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:formapi.lodev.xyz"
      - "traefik.port=3000"
      - "traefik.protocol=http"
      - "traefik.docker.network=web"

networks:
  db:
    external:
      name: db
  web:
    external:
      name: web
