version: '3.7'

volumes:
  postgres_data_form:
    driver: local

services:
  postgres_formapi:
    image: postgres:10-alpine
    restart: on-failure
    container_name: postgres_formapi
    volumes:
      - postgres_data_form:/var/lib/data/postgresqlform/data
    environment:
      POSTGRES_DB: formdb
      POSTGRES_USER: formuser
      POSTGRES_PASSWORD: password
    ports:
      - '5435:5432'
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U formuser formdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    labels:
      - "traefik.enable=false"

  formapi:
    build: .
    container_name: formapi
    environment:
      - NODE_ENV=production
      - DB_USERNAME=formuser
      - DB_PASSWORD=password
      - DB_NAME=formdb
      - DB_HOSTNAME=postgres_formapi
      - DB_PORT=5432
      - AUTH_URL=${AUTH_URL}
      - AUTH_BEARER_ONLY=true
      - AUTH_REALM=${AUTH_REALM}
      - ADMIN_ROLES=platform
      - ENABLE_LOG_CHANGE=false
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
    depends_on:
      - postgres_formapi
    networks:
      - web
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/healthz"]
      interval: 5s
      timeout: 2s
      retries: 15
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:formapi.${DOMAINNAME}"
      - "traefik.port=3000"
      - "traefik.protocol=http"
      - "traefik.docker.network=web"

networks:
  db:
    external:
      name: db
  web:
    external:
      name: web
