version: '3.7'

volumes:
  postgres_data_form:
    driver: local

services:
  postgres_formapi:
    image: postgres:10-alpine
    restart: on-failure
    container_name: postgres_formapi
    volumes:
      - postgres_data_form:/var/lib/data/postgresqlform/data
    environment:
      POSTGRES_DB: formdb
      POSTGRES_USER: formdb
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U formdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  formapi:
    build: .
    container_name: formapi
    environment:
      - NODE_ENV=production
      - DB_USERNAME=formdb
      - DB_PASSWORD=password
      - DB_NAME=formdb
      - DB_HOSTNAME=
      - DATABASE_URL=postgres://formdb:password@postgres_formapi:5432/formdb
      - AUTH_URL=http://keycloak.lodev.xyz/auth
      - AUTH_RESOURCE=form-api-server
      - AUTH_BEARER_ONLY=true
      - AUTH_REALM=dev
    depends_on:
      - postgres_formapi
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/heathz"]
      interval: 5s
      timeout: 2s
      retries: 15
      start_period: 30s

