---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.API_FORM_NAME}}"
spec:
  selector:
    matchLabels:
      name: "{{.API_FORM_NAME}}"
  replicas: 3
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: "{{.API_FORM_NAME}}"
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "{{.API_FORM_PORT}}"
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: {{.API_FORM_NAME}}-proxy
        image: "{{.NGINX_IMAGE}}:{{.NGINX_TAG}}"
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: "{{.API_FORM_PORT}}"
          - name: SERVER_CERT
            value: "/certs/tls.crt"
          - name: SERVER_KEY
            value: "/certs/tls.key"
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: STATSD_METRICS
            value: "FALSE"
        ports:
          - name: https
            containerPort: 10443
        volumeMounts:
          - name: certs
            mountPath: /certs
      - name: "{{.API_FORM_NAME}}"
        image: "{{.API_FORM_IMAGE}}:{{.API_FORM_TAG}}"
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: {{.API_FORM_PORT}}
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 15
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: {{.API_FORM_PORT}}
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 15
        env:
          - name: DB_FORM_DEFAULT_USERNAME
            value: "{{.DB_FORM_DEFAULT_USERNAME}}"
          - name: DB_FORM_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{.API_FORM_NAME}}"
                key: dbPassword
          - name: DB_FORM_HOSTNAME
            value: "{{.DB_FORM_HOSTNAME}}"
          - name: DB_FORM_DEFAULT_DBNAME
            value: "{{.DB_FORM_DEFAULT_DBNAME}}"
          - name: DB_FORM_PORT
            value: "{{.DB_FORM_PORT}}"
          - name: DB_FORM_SSL
            value: "{{.DB_FORM_SSL}}"
          - name: KEYCLOAK_PROTOCOL
            value: "{{.KEYCLOAK_PROTOCOL}}"
          - name: KEYCLOAK_URL
            value: "{{.KEYCLOAK_URL}}"
          - name: KEYCLOAK_REALM
            value: "{{.KEYCLOAK_REALM}}"
          - name: API_FORM_KEYCLOAK_CLIENT_ID
            value: "{{.API_FORM_KEYCLOAK_CLIENT_ID}}"
          - name: API_FORM_KEYCLOAK_BEARER_ONLY
            value: "{{.API_FORM_KEYCLOAK_BEARER_ONLY}}"
          - name: API_FORM_KEYCLOAK_ADMIN_USERNAME
            value: "{{.API_FORM_KEYCLOAK_ADMIN_USERNAME}}"
          - name: API_FORM_KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{.API_FORM_NAME}}"
                key: authAdminPassword
          - name: API_FORM_KEYCLOAK_ADMIN_CLIENT_ID
            value: "{{.API_FORM_KEYCLOAK_ADMIN_CLIENT_ID}}"
          - name: API_FORM_KEYCLOAK_ROLES
            value: "{{.API_FORM_KEYCLOAK_ROLES}}"
          - name: API_FORM_LOG_ENABLE_CHANGE
            value: "{{.API_FORM_LOG_ENABLE_CHANGE}}"
          - name: API_FORM_LOG_ENABLE_QUERY
            value: "{{.API_FORM_LOG_ENABLE_QUERY}}"
          - name: API_FORM_LOG_CHANGE_TIMEOUT
            value: "{{.API_FORM_LOG_CHANGE_TIMEOUT}}"
          - name: API_FORM_CACHE_ROLE_MAX_AGE
            value: "{{.API_FORM_CACHE_ROLE_MAX_AGE}}"
          - name: API_FORM_CACHE_ROLE_MAX_ENTRIES
            value: "{{.API_FORM_CACHE_ROLE_MAX_ENTRIES}}"
          - name: API_FORM_CACHE_FORM_MAX_AGE
            value: "{{.API_FORM_CACHE_FORM_MAX_AGE}}"
          - name: API_FORM_CACHE_FORM_MAX_ENTRIES
            value: "{{.API_FORM_CACHE_FORM_MAX_ENTRIES}}"
          - name: API_FORM_CACHE_USER_ROLE_ENTRIES
            value: "{{.API_FORM_CACHE_USER_ROLE_ENTRIES}}"
          - name: API_FORM_CACHE_USER_FORM_ENTRIES
            value: "{{.API_FORM_CACHE_USER_FORM_ENTRIES}}"
          - name: API_FORM_CACHE_USER_MAX_AGE
            value: "{{.API_FORM_CACHE_USER_MAX_AGE}}"
          - name: API_FORM_CACHE_USER_MAX_ENTRIES
            value: "{{.API_FORM_CACHE_USER_MAX_ENTRIES}}"
          - name: API_FORM_BUSINESS_KEY_PREFIX
            value: "{{.API_FORM_BUSINESS_KEY_PREFIX}}"
          - name: API_FORM_BUSINESS_KEY_ENABLED
            value: "{{.API_FORM_BUSINESS_KEY_ENABLED}}"
          - name: API_FORM_EDIT_ROLES
            value: "{{.API_FORM_EDIT_ROLES}}"
          - name: API_FORM_PORT
            value: "{{.API_FORM_PORT}}"
          - name: REDIS_PORT
            value: "{{.REDIS_PORT}}"
          - name: REDIS_SSL
            value: "{{.REDIS_SSL}}"
          - name: REDIS_URI
            value: "{{.REDIS_URL}}"
          - name: REDIS_TOKEN
            valueFrom:
              secretKeyRef:
                name: "{{.API_FORM_NAME}}"
                key: redisToken
      volumes:
      - name: certs
        secret:
          secretName: "{{.API_FORM_NAME}}-pod-cmio"
