apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    stable.k8s.psg.io/kcm.provider: http
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  labels:
    app.kubernetes.io/name: {{.API_FORM_NAME}}
    stable.k8s.psg.io/kcm.class: default
  name: {{.API_FORM_NAME}}
spec:
  rules:
  - host: {{.API_FORM_URL}}
    http:
      paths:
      - backend:
          serviceName: {{.API_FORM_NAME}}
          servicePort: 443
  tls:
  - hosts:
    - {{.API_FORM_URL}}
    secretName: {{.API_FORM_URL}}-tls
