apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/enabled: "true"
    ingress.kubernetes.io/backend-protocol: HTTPS
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-read-timeout: "3600"
    ingress.kubernetes.io/proxy-send-timeout: "3600"
    kubernetes.io/ingress.class: nginx-external
  labels:
    app.kubernetes.io/name: {{.API_FORM_NAME}}
    cert-manager.io/solver: http01
  name: {{.API_FORM_NAME}}
spec:
  rules:
  - host: {{.API_FORM_URL}}
    http:
      paths:
      - backend:
          serviceName: {{.API_FORM_NAME}}
          servicePort: 443
  tls:
  - hosts:
    - {{.API_FORM_URL}}
    secretName: {{.API_FORM_URL}}-cmio
