---
apiVersion: v1
kind: Secret
metadata:
  name: {{.API_FORM_NAME}}
type: Opaque
data:
  dbPassword: {{.DB_FORM_DEFAULT_PASSWORD | b64enc}}
  authAdminPassword: {{.API_FORM_KEYCLOAK_ADMIN_PASSWORD | b64enc }}
  redisToken: {{.REDIS_TOKEN | b64enc}}