---
apiVersion: v1
kind: Secret
metadata:
  name: {{.FORM_NAME}}
type: Opaque
data:
  dbPassword: {{.DB_FORM_DEFAULT_PASSWORD | b64enc}}
  authAdminPassword: {{.FORM_KEYCLOAK_ADMIN_PASSWORD | b64enc }}