---
apiVersion: v1
kind: Secret
metadata:
  name: {{.FORM_API_NAME}}
type: Opaque
data:
  dbPassword: {{.FORM_API_DB_PASSWORD | b64enc}}
  authAdminPassword: {{.FORM_API_KEYCLOAK_ADMIN_PASSWORD | b64enc }}